// Generated by CoffeeScript 1.8.0
(function() {
  describe('first', function() {
    var arr;
    arr = null;
    beforeEach(function() {
      return arr = [5, 4, 3, 2, 1];
    });
    it('should return the first element of an array when no argument is provided', function() {
      var result;
      result = _.first(arr);
      return expect(result).toEqual(5);
    });
    it('should return the first n elements of an array when passed n as an argument', function() {
      var result;
      result = _.first(arr, 3);
      return expect(result).toEqual([5, 4, 3]);
    });
    return it('should return all the elements if n is greater than or equal to the arrays length', function() {
      var result;
      result = _.first(arr, 20);
      return expect(result).toEqual(arr);
    });
  });

}).call(this);
