// Generated by CoffeeScript 1.8.0
(function() {
  describe('objects', function() {
    describe('_.keys', function() {
      return it('should return all of the names of the object\'s properties', function() {
        var results;
        results = _.keys({
          one: 1,
          two: 2,
          three: 3
        });
        return expect(results).toEqual(['one', 'two', 'three']);
      });
    });
    describe('_.values', function() {
      return it('should return all of the values of the object\'s properties', function() {
        var results;
        results = _.values({
          one: 1,
          two: 2,
          three: 3
        });
        return expect(results).toEqual([1, 2, 3]);
      });
    });
    describe('_.pairs', function() {
      return it('should convert an object into a list of [key, value] pairs', function() {
        var results;
        results = _.pairs({
          one: 1,
          two: 2,
          three: 3
        });
        return expect(results).toEqual([["one", 1], ["two", 2], ["three", 3]]);
      });
    });
    return describe('_.invert', function() {
      return it('should return a copy of the object where the keys and values have been swapped', function() {
        var results;
        results = _.invert({
          Moe: "Moses",
          Larry: "Louis",
          Curly: "Jerome"
        });
        return expect(results).toEqual({
          Moses: "Moe",
          Louis: "Larry",
          Jerome: "Curly"
        });
      });
    });
  });

}).call(this);
