// Generated by CoffeeScript 1.8.0
(function() {
  var checkObjectForProperties, checkObjectForProperty,
    __hasProp = {}.hasOwnProperty;

  window._ = {};

  _.each = function(container, callback, context) {
    var index, item, key, value, _i, _len, _results, _results1;
    if (context == null) {
      context = this;
    }
    if (Array.isArray(container)) {
      _results = [];
      for (index = _i = 0, _len = container.length; _i < _len; index = ++_i) {
        item = container[index];
        _results.push(callback.call(context, item, index, container));
      }
      return _results;
    } else {
      _results1 = [];
      for (key in container) {
        if (!__hasProp.call(container, key)) continue;
        value = container[key];
        _results1.push(callback.call(context, value, key, container));
      }
      return _results1;
    }
  };

  _.map = function(container, callback, context) {
    var index, item, key, value, _i, _len, _results, _results1;
    if (context == null) {
      context = this;
    }
    callback = callback || function(value) {
      return value;
    };
    if (Array.isArray(container)) {
      _results = [];
      for (index = _i = 0, _len = container.length; _i < _len; index = ++_i) {
        item = container[index];
        _results.push(callback.call(context, item, index, container));
      }
      return _results;
    } else {
      _results1 = [];
      for (key in container) {
        if (!__hasProp.call(container, key)) continue;
        value = container[key];
        _results1.push(callback.call(context, value, key, container));
      }
      return _results1;
    }
  };

  _.reduce = function(container, callback, startingValue, context) {
    var iteratee;
    if (startingValue == null) {
      startingValue = 0;
    }
    if (context == null) {
      context = this;
    }
    iteratee = function(element, index, container) {
      return startingValue = callback.call(context, startingValue, element, index, container);
    };
    _.each(container, iteratee, context);
    return startingValue;
  };

  _.find = function(container, callback, context) {
    var result;
    if (context == null) {
      context = this;
    }
    result = void 0;
    _.each(container, function(value, index, container) {
      if (result === void 0 && callback.call(context, value) === true) {
        return result = value;
      }
    });
    return result;
  };

  _.detect = _.find;

  _.filter = function(container, callback, context) {
    var results;
    if (context == null) {
      context = this;
    }
    results = [];
    _.each(container, function(value, index, container) {
      if (callback.call(context, value)) {
        return results.push(value);
      }
    });
    return results;
  };

  _.select = _.filter;

  _.where = function(container, properties) {
    var results;
    results = [];
    _.each(container, function(value, index, container) {
      if (checkObjectForProperties(value, properties)) {
        return results.push(value);
      }
    });
    return results;
  };

  checkObjectForProperties = function(object, properties) {
    var key;
    for (key in properties) {
      if (!checkObjectForProperty(key, properties[key], object)) {
        return false;
      }
    }
    return true;
  };

  checkObjectForProperty = function(key, value, object) {
    var otherKey;
    for (otherKey in object) {
      if (otherKey === key && value === object[key]) {
        return true;
      }
    }
    return false;
  };

  _.findWhere = function(container, properties) {
    return _.where(container, properties)[0];
  };

  _.reject = function(container, callback, context) {
    if (context == null) {
      context = this;
    }
    return _.filter(container, function(value) {
      return !callback.call(context, value);
    });
  };

  _.every = function(container, callback, context) {
    var status;
    if (context == null) {
      context = this;
    }
    status = true;
    _.each(container, function(value) {
      if (!callback.call(context, value)) {
        return status = false;
      }
    });
    return status;
  };

  _.all = _.every;

  _.some = function(container, callback, context) {
    if (context == null) {
      context = this;
    }
    return _.filter(container, callback, context).length !== 0;
  };

  _.any = _.some;

  _.contains = function(container, value) {
    return _.some(container, function(element) {
      return element === value;
    });
  };

  _.include = _.contains;

  _.invoke = function(container, methodName) {
    var args;
    args = [].slice.call(arguments, 2);
    return _.map(container, function(value) {
      return value[methodName].apply(value, args);
    });
  };

  _.pluck = function(container, key) {
    return _.map(container, function(obj) {
      return obj[key];
    });
  };

  _.max = function(container, callback, context) {
    var maxVal, result;
    if (context == null) {
      context = this;
    }
    result = void 0;
    maxVal = void 0;
    _.each(container, function(value) {
      var count;
      if (callback) {
        count = callback.call(context, value);
      } else {
        count = value;
      }
      maxVal = maxVal || count;
      result = result || value;
      if (count > maxVal) {
        return result = value;
      }
    });
    return result || Number.POSITIVE_INFINITY;
  };

  _.min = function(container, callback, context) {
    var minVal, result;
    if (context == null) {
      context = this;
    }
    result = void 0;
    minVal = void 0;
    _.each(container, function(value) {
      var count;
      if (callback) {
        count = callback.call(context, value);
      } else {
        count = value;
      }
      minVal = minVal || count;
      result = result || value;
      if (count < minVal) {
        return result = value;
      }
    });
    return result || Number.POSITIVE_INFINITY;
  };

  _.sortBy = function(container, iteratee, context) {
    if (context == null) {
      context = this;
    }
    return _.map(_.map(container, (function(value) {
      return {
        key: iteratee(value),
        value: value
      };
    }), context).sort(function(a, b) {
      return a.key > b.key;
    }), function(obj) {
      return obj.value;
    }, context);
  };

  _.organizeBy = function(container, iteratee) {
    var getKey;
    getKey = function(value, iteratee) {
      if (typeof iteratee === "string") {
        return value[iteratee];
      } else {
        return iteratee(value);
      }
    };
    return _.map(container, function(value) {
      return {
        key: getKey(value, iteratee),
        value: value
      };
    });
  };

  _.groupBy = function(container, iteratee, context) {
    var result;
    if (context == null) {
      context = this;
    }
    result = {};
    _.each(_.organizeBy(container, iteratee, context), function(obj) {
      if (result[obj.key] === void 0) {
        result[obj.key] = [];
      }
      return result[obj.key].push(obj.value);
    });
    return result;
  };

  _.indexBy = function(container, iteratee, context) {
    var result;
    if (context == null) {
      context = this;
    }
    result = {};
    _.each(_.organizeBy(container, iteratee, context), function(obj) {
      return result[obj.key] = obj.value;
    });
    return result;
  };

  _.countBy = function(container, iteratee, context) {
    var result;
    if (context == null) {
      context = this;
    }
    result = {};
    _.each(_.organizeBy(container, iteratee, context), function(obj) {
      if (result[obj.key] === void 0) {
        result[obj.key] = 0;
      }
      return result[obj.key] += 1;
    });
    return result;
  };

  _.shuffle = function(container) {
    var popRandomElementFrom, size;
    if (!Array.isArray(container)) {
      container = _.map(container, function(value) {
        return value;
      });
    }
    size = container.length - 1;
    popRandomElementFrom = function(array, index) {
      var element;
      element = array[index];
      array[index] = array[size];
      size -= 1;
      return element;
    };
    return _.map(container, function() {
      return popRandomElementFrom(container, Math.floor(Math.random() * size));
    });
  };

}).call(this);
