// Generated by CoffeeScript 1.8.0
(function() {
  _.keys = function(obj) {
    return _.map(obj, function(value, key) {
      return key;
    });
  };

  _.values = function(obj) {
    return _.map(obj, function(value) {
      return value;
    });
  };

  _.pairs = function(obj) {
    return _.map(obj, function(value, key) {
      return [key, value];
    });
  };

}).call(this);
