// Generated by CoffeeScript 1.9.3
(function() {
  _.identity = function(value) {
    return value;
  };

  _.constant = function(value) {
    return function() {
      return value;
    };
  };

  _.noop = function() {
    return void 0;
  };

  _.times = function(n, iteratee, context) {
    var i, j, ref, results;
    results = [];
    for (i = j = 1, ref = n; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
      results.push(iteratee.call(context, i));
    }
    return results;
  };

  _.random = function(min, max) {
    if (min === void 0) {
      return NaN;
    }
    if (max === void 0) {
      max = min;
      min = 0;
    }
    return min + Math.floor(Math.random() * (max - min + 1));
  };

  _.mixin = function(fns) {
    var name, results;
    results = [];
    for (name in fns) {
      results.push(_[name] = fns[name]);
    }
    return results;
  };

  _.storage = {};

  _.uniqueId = function(name) {
    _.storage[name] = _.storage[name] || 0;
    return name + ++_.storage[name];
  };

  _.escapeChar = {};

  _.escapeChar['&'] = '&#38;';

  _.escapeChar['<'] = '&#60;';

  _.escapeChar['>'] = '&#62;';

  _.escapeChar['"'] = '&#34;';

  _.escapeChar['\''] = '&#39;';

  _.escapeChar['`'] = '&#96;';

  _.escape = function(str) {
    var i, j, len, newStr;
    newStr = '';
    for (j = 0, len = str.length; j < len; j++) {
      i = str[j];
      newStr += _.escapeChar[i] || i;
    }
    return newStr;
  };

  _.escapeChar['&#38;'] = '&';

  _.escapeChar['&#60;'] = '<';

  _.escapeChar['&#62;'] = '>';

  _.escapeChar['&#34;'] = '"';

  _.escapeChar['&#39;'] = '\'';

  _.escapeChar['&#96;'] = '`';

  _.unescape = function(str) {
    var escapeChar, i, newStr;
    newStr = '';
    i = 0;
    while (i < str.length) {
      escapeChar = _.escapeChar[str.substring(i, i + 5)];
      if (escapeChar) {
        newStr += escapeChar;
        i += 4;
      } else {
        newStr += str[i];
      }
      i++;
    }
    return newStr;
  };

}).call(this);
